title: "개발 블로그"
description: "개발 기록지"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: "dkswoals1003@gmail.com"
github_username: "woalswoals1003"
twitter_username: ""
instagram_username: ""
linkedin_username: ""
facebook_username: ""

# External API
giscus_repo: ""
giscus_repoId: ""
giscus_category: ""
giscus_categoryId: ""
goatcounter_code: ""
google_analytics: ""

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
